server :
  port :  9009
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=zjsysbxytq
      username: sa
      password: qwer1234com
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      type: com.alibaba.druid.pool.DruidDataSource

#配置分页插件
#pagehelper分页插件
pagehelper:
  helper-dialect: sqlserver
  reasonable: true
  support-methods-arguments: true
  params:
    count: countSql

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lhtg.unorganized_control.mapper
  configLocation:
    classpath: mybatis-config.xml
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
