server :
  port :  9876
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
      url: jdbc:sqlserver://10.32.2.237:1433;DatabaseName=hxjy
      username: sa
      password: 123456
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#pagehelper分页插件
pagehelper:
  helper-dialect: sqlserver
  reasonable: true
  support-methods-arguments: true
  params:
    count: countSql

mybatis:
  mapper-locations: classpath*:/resources/mapper/*Mapper.xml
  type-aliases-package: com.lhtg.unorganized_control.mapper
  configLocation:
    classpath: mybatis-config.xml
